changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
      - github-actions

  categories:
    - title: "Breaking Changes"
      labels:
        - breaking-change

    - title: "New Features"
      labels:
        - enhancement
        - feature

    - title: "Bug Fixes"
      labels:
        - bug
        - fix

    - title: "Documentation"
      labels:
        - documentation

    - title: "Other Changes"
      labels:
        - "*"
